[project]
name = "espminer-optim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "optuna>=4.2.1",
    "optuna-dashboard>=0.18.0",
    "pandas>=2.2.3",
    "requests>=2.32.3",
    "rich>=14.0.0",
    "ruff>=0.11.5",
]
